[package]
name = "robonomics-node"
version = "0.9.0"
authors = ["Airalab <research@aira.life>"]
build = "build.rs"

[[bin]]
name = "robonomics"
path = "src/main.rs"

[dependencies]
slog = "^2"
tokio = "0.1.7"
futures = "0.1"
serde_json = "1.0"
error-chain = "0.12"
ctrlc = { version = "3.0", features = ["termination"] }
exit-future = "0.1"
parking_lot = "0.4"
substrate-transaction-pool = { git = "https://github.com/paritytech/substrate" }
substrate-finality-grandpa = { git = "https://github.com/paritytech/substrate" }
substrate-basic-authorship = { git = "https://github.com/paritytech/substrate" }
substrate-consensus-aura = { git = "https://github.com/paritytech/substrate" }
substrate-primitives = { git = "https://github.com/paritytech/substrate" }
substrate-telemetry = { git = "https://github.com/paritytech/substrate" }
substrate-inherents = { git = "https://github.com/paritytech/substrate" }
substrate-keystore = { git = "https://github.com/paritytech/substrate" }
substrate-executor = { git = "https://github.com/paritytech/substrate" }
substrate-service = { git = "https://github.com/paritytech/substrate" }
substrate-network = { git = "https://github.com/paritytech/substrate" }
substrate-client = { git = "https://github.com/paritytech/substrate", default-features = false }
substrate-cli = { git = "https://github.com/paritytech/substrate" }
ros-integration = { path = "ros-integration", optional = true }
robonomics-runtime = { path = "runtime" }

[features]
default = []

## Enable ROS integration: exports to ROS topics and services for Robonomics communication.
# To build with it install ROS (http://wiki.ros.org/melodic/Installation) before.
# It also require roscore to be launched to start.
ros = [ 'ros-integration' ]

[build-dependencies]
vergen = "2"

[workspace]
members = [ "runtime", "ros-integration", "parachain/collator" ]
exclude = [ "runtime/wasm", "parachain/wasm" ]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
